apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-crud-deployment # Name of the deployment
spec:
  selector:
    matchLabels:
      app: spring-k8s-mysql  # He said this is selector
  replicas: 3  # This will create 3 pods
  template:
    metadata:
      labels:
        app: spring-k8s-mysql
    spec:
      containers:
        - name: spring-k8s-crud
          image: syamaira/spring-crud:v0 # docker image that needs to be used
          imagePullPolicy: IfNotPresent # simple way to enforce image pulling
          ports:
            - containerPort: 8081  # I believe this is the port that configured in application.yml file of docker
          env:   # Setting Environment Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            - name: DB_NAME   # Setting Database name from a ConfigMap
              value: testdb

            - name: DB_USERNAME   # Setting Database username from secrets
              value: root

            - name: DB_PASSWORD   # Setting Database password from secrets
              value: root

---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource(name of the service) kind we are creating
  name: spring-crud-svc
spec:
  selector:
    app: spring-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081
      nodePort: 30001 # The port exposed by the service (30000 to 32767)
  type: NodePort
  # ClusterIP : Pod-to-Pod communication within the same cluster.
  # NodePort : I defined this since I want to connect to this instance from workbench (external clients)
  # LoadBalancer : external clients, it only works if you're using Kubernetes on a cloud platform that supports this Service type.
  # ExternalName: Maps a service to an external DNS name.Used for redirecting traffic to an external service.